CATEGORIES:
 - person
 - skill
 - project

RELATIONSHIPS:
 'project, person': is_being_developed_by
 'person, skill': proficient_in
 'project, skill': requires
 
AUTHENTICATION:
 uri: add uri here
 username: add username here
 password: add password here